# Adding & Removing Rows and Columns in Pandas

In [2]:
import pandas as pd

In [3]:
# Sample Titanic-like data
data = {
    "Name": ["sudip", "sansa", "seema", "Sushant"],
    "Age": [18, 19, 22, 26],
    "Sex": ["male", "female", "male", "male"],
    "Survived": [1, 1, 0, 1],
    "Fare": [50, 100, 30, 60]
}

df = pd.DataFrame(data)
df

      Name  Age     Sex  Survived  Fare
0    sudip   18    male         1    50
1    sansa   19  female         1   100
2    seema   22    male         0    30
3  Sushant   26    male         1    60

In [4]:
# Add a new column with default value
# Using .loc to add column
df.loc[:, "Embarked"] = "C"
df

      Name  Age     Sex  Survived  Fare Embarked
0    sudip   18    male         1    50        C
1    sansa   19  female         1   100        C
2    seema   22    male         0    30        C
3  Sushant   26    male         1    60        C

In [5]:
# Add a column based on calculation
df.loc[:, "Fare_after_tax"] = df["Fare"] * 1.10
df

      Name  Age     Sex  Survived  Fare Embarked  Fare_after_tax
0    sudip   18    male         1    50        C            55.0
1    sansa   19  female         1   100        C           110.0
2    seema   22    male         0    30        C            33.0
3  Sushant   26    male         1    60        C            66.0

In [6]:
df

      Name  Age     Sex  Survived  Fare Embarked  Fare_after_tax
0    sudip   18    male         1    50        C            55.0
1    sansa   19  female         1   100        C           110.0
2    seema   22    male         0    30        C            33.0
3  Sushant   26    male         1    60        C            66.0

In [7]:
# add another columns
df.loc[1:3,"Age increase"]=df["Age"]+20
df

      Name  Age     Sex  Survived  Fare Embarked  Fare_after_tax  Age increase
0    sudip   18    male         1    50        C            55.0           NaN
1    sansa   19  female         1   100        C           110.0          39.0
2    seema   22    male         0    30        C            33.0          42.0
3  Sushant   26    male         1    60        C            66.0          46.0

In [8]:
# Keep only selected columns using .loc
df=df.loc[:, ["Name", "Age", "Sex", "Survived", "Fare"]]

In [9]:
df

      Name  Age     Sex  Survived  Fare
0    sudip   18    male         1    50
1    sansa   19  female         1   100
2    seema   22    male         0    30
3  Sushant   26    male         1    60

In [10]:
df

      Name  Age     Sex  Survived  Fare
0    sudip   18    male         1    50
1    sansa   19  female         1   100
2    seema   22    male         0    30
3  Sushant   26    male         1    60

In [11]:
df.loc[5] = {"Name": "Leo", "Age": 30, "Sex": "male"}
# add new rows using the dictionary

In [12]:
df

      Name  Age     Sex  Survived   Fare
0    sudip   18    male       1.0   50.0
1    sansa   19  female       1.0  100.0
2    seema   22    male       0.0   30.0
3  Sushant   26    male       1.0   60.0
5      Leo   30    male       NaN    NaN

for dictionary
Pandas will automatically fill missing columns with NaN.

Task: fecth multiple rows at the same time

In [13]:
df.loc[[0, 3]]

      Name  Age   Sex  Survived  Fare
0    sudip   18  male       1.0  50.0
3  Sushant   26  male       1.0  60.0

In [20]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'Name': ['jeni', 'anish', 'naira'],
    'Age': [15, 20, 28],
    'Sex': ['female', 'male', 'female']
})
df

    Name  Age     Sex
0   jeni   15  female
1  anish   20    male
2  naira   28  female

In [21]:
# Change Bob's Age and Sex
df.loc[df['Name'] == 'sweety', ['Age', 'Sex']] = [22, 'male']

df

    Name  Age     Sex
0   jeni   15  female
1  anish   20    male
2  naira   28  female

In [22]:
# Changes multiple columns
df.loc[df['Name'] == 'jeni', ['Age', 'Sex', 'Status']] = [29, 'female', 'single']

df

    Name  Age     Sex  Status
0   jeni   29  female  single
1  anish   20    male     NaN
2  naira   28  female     NaN

In [17]:
df.loc[:,["height","weight"]]=[5.3,55]

task: how to add different weight and height for the each person

In [23]:
df.loc[:, 'Height'] = [5.3, 5.8, 5.5]
df.loc[:, 'Weight'] = [55, 65, 60]

df

    Name  Age     Sex  Status  Height  Weight
0   jeni   29  female  single     5.3      55
1  anish   20    male     NaN     5.8      65
2  naira   28  female     NaN     5.5      60

In [24]:
df[df['Name'] == 'Clara'][['Age', 'Sex', 'Status']] = [29, 'female', 'Married']

In [25]:
df

    Name  Age     Sex  Status  Height  Weight
0   jeni   29  female  single     5.3      55
1  anish   20    male     NaN     5.8      65
2  naira   28  female     NaN     5.5      60

In [27]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'Name': ['subash', 'krion', 'seion'],
    'Age': [20, 10, 28]
})
df

     Name  Age
0  subash   20
1   krion   10
2   seion   28

In [28]:
# Add a new column 'Sex'
df.loc[:, 'Sex'] = ['female', 'male', 'female']

df

     Name  Age     Sex
0  subash   20  female
1   krion   10    male
2   seion   28  female

In [29]:
df.set_index("Age",inplace=True)

In [30]:
df

       Name     Sex
Age
20   subash  female
10    krion    male
28    seion  female

In [32]:
df.loc[20,"Sex"]

'female'

### Examples of when you need `inplace=True` (including index operations)

| Operation | Default behavior | With `inplace=True` |
|-----------|----------------|------------------|
| `df.drop("x", axis=1)` | Returns a new DataFrame without column `"x"`; original `df` stays the same | Original `df` loses column `"x"` |
| `df.drop(0, axis=0)` | Returns a new DataFrame without row 0; original `df` unchanged | Original `df` loses row 0 |
| `df.sort_values("col")` | Returns a sorted copy; original `df` unchanged | Original `df` is sorted |
| `df.sort_index()` | Returns a copy sorted by index; original `df` unchanged | Original `df` is sorted by index |
| `df.fillna(0)` | Returns a copy with NaNs replaced | Original `df` modified |
| `df.rename(columns={"old":"new"})` | Returns a copy with renamed columns | Original `df` modified |
| `df.rename(index={0:"zero"})` | Returns a copy with renamed index | Original `df` index modified |
| `df.set_index("col")` | Returns a new DataFrame with `"col"` as index; original df unchanged | Original `df` now uses `"col"` as index |
| `df.reset_index()` | Returns a copy with index reset; original df unchanged | Original `df` index reset |