In [13]:
import pandas as pd

In [14]:
import pandas as pd

df = pd.read_csv("/content/titanic_dataset.csv")
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [15]:
# syntax for loc
#df.loc[row_condition, column_selection]

In [16]:
df[df["Age"]>30]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1295,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
1298,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
1302,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S

In [17]:
df.loc[df["Age"] > 30, :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1295,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
1298,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
1302,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S

In [18]:
# Passengers who survived
df.loc[df["Survived"] == 1, ["Name","Age","Survived"]]

                                                   Name   Age  Survived
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                                Heikkinen, Miss. Laina  26.0         1
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0         1
9                   Nasser, Mrs. Nicholas (Adele Achem)  14.0         1
...                                                 ...   ...       ...
1300                          Peacock, Miss. Treasteall   3.0         1
1301                             Naughton, Miss. Hannah   NaN         1
1302    Minahan, Mrs. William Edward (Lillian E Thorpe)  37.0         1
1303                     Henriksson, Miss. Jenny Lovisa  28.0         1
1305                       Oliva y Ocana, Dona. Fermina  39.0         1

[494 rows x 3 columns]

In [19]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1307,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1308,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [20]:
#Passengers in 1st class
df.loc[df["Pclass"]==1,["Name","Age","Pclass","Sex"]]

                                                   Name   Age  Pclass     Sex
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0       1  female
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0       1  female
6                               McCarthy, Mr. Timothy J  54.0       1    male
11                             Bonnell, Miss. Elizabeth  58.0       1  female
23                         Sloper, Mr. William Thompson  28.0       1    male
...                                                 ...   ...     ...     ...
1294                             Carrau, Mr. Jose Pedro  17.0       1    male
1295                       Frauenthal, Mr. Isaac Gerald  43.0       1    male
1298                         Widener, Mr. George Dunton  50.0       1    male
1302    Minahan, Mrs. William Edward (Lillian E Thorpe)  37.0       1  female
1305                       Oliva y Ocana, Dona. Fermina  39.0       1  female

[323 rows x 4 columns]

In [21]:
# Age > 30 AND Survived
df.loc[(df["Age"] > 30) & (df["Survived"] == 0), :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
1290,1291,0,3,"Conlon, Mr. Thomas Henry",male,31.0,0,0,21332,7.7333,NaN,Q
1292,1293,0,2,"Gale, Mr. Harry",male,38.0,1,0,28664,21.0000,NaN,S
1295,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,D40,C
1298,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S

In [33]:
# Age < 18 OR Female

age = 20
gender = "Female"

if age < 18 or gender == "Female":
    print("Condition is True")

Condition is True

# make a 5 question  live and practice

In [36]:
# 1. Age < 18 OR Female

age = 16
gender = "Male"

if age < 18 or gender == "False":
    print("True")
else:
    print("False")

True

In [37]:
# 2. Female

age = 25
gender = "Female"

if age < 18 or gender == "Female":
    print("True")
else:
    print("False")

True

In [38]:
# 3. Both Conditions False

age = 20
gender = "Male"

if age < 18 or gender == "Female":
    print("Eligible")
else:
    print("Not Eligible")

Not Eligible

In [44]:
# 4. Age < 18 OR Student

age = 20
student = True

if age < 18 or student == True:
    print("True")
else:
    print("False")

True

In [45]:
# 5. Age and Gender

age = 30
gender = "Male"

if age < 18 or gender == "Female":
    print("Condition is True")
else:
    print("Condition is False")

Condition is False

In [46]:
# find out the members numbers  of 3rd class who is female
df.loc[(df["Pclass"]==3) & (df["Sex"]=="female"),["Pclass","Sex","Name"]]

      Pclass     Sex                                               Name
2          3  female                             Heikkinen, Miss. Laina
8          3  female  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
10         3  female                    Sandstrom, Miss. Marguerite Rut
14         3  female               Vestrom, Miss. Hulda Amanda Adolfina
18         3  female  Vander Planke, Mrs. Julius (Emelia Maria Vande...
...      ...     ...                                                ...
1274       3  female                McNamee, Mrs. Neal (Eileen O'Leary)
1299       3  female                    Riordan, Miss. Johanna Hannah""
1300       3  female                          Peacock, Miss. Treasteall
1301       3  female                             Naughton, Miss. Hannah
1303       3  female                     Henriksson, Miss. Jenny Lovisa

[216 rows x 3 columns]

In [50]:
# Female passengers older than 25
df.loc[(df["Sex"] == "female") & (df["Age"] > 25), ["Name", "Age", "Pclass"]]

                                                   Name   Age  Pclass
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0       1
2                                Heikkinen, Miss. Laina  26.0       3
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0       1
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0       3
11                             Bonnell, Miss. Elizabeth  58.0       1
...                                                 ...   ...     ...
1288  Frolicher-Stehli, Mrs. Maxmillian (Margaretha ...  48.0       1
1291                            Bonnell, Miss. Caroline  30.0       1
1302    Minahan, Mrs. William Edward (Lillian E Thorpe)  37.0       1
1303                     Henriksson, Miss. Jenny Lovisa  28.0       3
1305                       Oliva y Ocana, Dona. Fermina  39.0       1

[210 rows x 3 columns]

In [51]:
# Average age of survivors
df.loc[df["Survived"]==1,"Age"].mean()

np.float64(28.93107913669065)

In [52]:
#Rich passengers (Fare > 100) who survived only find name and age

rich_survived = df[(df["Fare"] > 100) & (df["Survived"] == 1)]

print(rich_survived[["Name", "Age"]])

                                                   Name    Age
31       Spencer, Mrs. William Augustus (Marie Eugenie)    NaN
88                           Fortune, Miss. Mabel Helen  23.00
195                                Lurette, Miss. Elise  58.00
215                             Newell, Miss. Madeleine  31.00
258                                    Ward, Miss. Anna  35.00
268       Graham, Mrs. William Thompson (Edith Junkins)  58.00
269                              Bissette, Miss. Amelia  35.00
299     Baxter, Mrs. James (Helene DeLaudeniere Chaput)  50.00
305                      Allison, Master. Hudson Trevor   0.92
306                             Fleming, Miss. Margaret    NaN
307   Penasco y Castellana, Mrs. Victor de Satode (M...  17.00
311                          Ryerson, Miss. Emily Borie  18.00
318                            Wick, Miss. Mary Natalie  31.00
319   Spedden, Mrs. Frederic Oakley (Margaretta Corn...  40.00
325                            Young, Miss. Marie Grice  36.00
334   Frauenthal, Mrs. Henry William (Clara Heinshei...    NaN
337                     Burns, Miss. Elizabeth Margaret  41.00
341                      Fortune, Miss. Alice Elizabeth  24.00
380                               Bidois, Miss. Rosalie  42.00
390                          Carter, Mr. William Ernest  36.00
393                              Newell, Miss. Marjorie  23.00
435                           Carter, Miss. Lucile Polk  14.00
537                                 LeRoy, Miss. Bertha  30.00
550                         Thayer, Mr. John Borland Jr  17.00
581   Thayer, Mrs. John Borland (Marian Longstreth M...  39.00
609                           Shutes, Miss. Elizabeth W  40.00
660                       Frauenthal, Dr. Henry William  50.00
679                  Cardeza, Mr. Thomas Drake Martinez  36.00
689                   Madill, Miss. Georgette Alexandra  15.00
700   Astor, Mrs. John Jacob (Madeleine Talmadge Force)  18.00
708                                Cleaver, Miss. Alice  22.00
716                       Endres, Miss. Caroline Louise  38.00
730                       Allen, Miss. Elisabeth Walton  29.00
737                              Lesurer, Mr. Gustave J  35.00
742               Ryerson, Miss. Susan Parker "Suzette"  21.00
763           Carter, Mrs. William Ernest (Lucile Polk)  36.00
779   Robert, Mrs. Edward Scott (Elisabeth Walton Mc...  43.00
802                 Carter, Master. William Thornton II  11.00
856          Wick, Mrs. George Dennick (Mary Hitchcock)  45.00
915     Ryerson, Mrs. Arthur Larned (Emily Maria Borie)  48.00
944                          Fortune, Miss. Ethel Flora  28.00
950                         Chaudanson, Miss. Victorine  36.00
960                 Fortune, Mrs. Mark (Mary McDougald)  60.00
965                                Geiger, Miss. Amalie  35.00
1005             Straus, Mrs. Isidor (Rosalie Ida Blun)  63.00
1032                               Daniels, Miss. Sarah  33.00
1047                                  Bird, Miss. Ellen  29.00
1075  Douglas, Mrs. Frederick Charles (Mary Helene B...  27.00
1109       Widener, Mrs. George Dunton (Eleanor Elkins)  50.00
1130        Douglas, Mrs. Walter Donald (Mahala Dutton)  48.00
1163      Clark, Mrs. Walter Miller (Virginia McDowell)  26.00
1205              White, Mrs. John Stuart (Ella Holmes)  55.00
1215                             Kreuchen, Miss. Emilie  39.00
1234  Cardeza, Mrs. James Warburton Martinez (Charlo...  58.00
1262                          Wilson, Miss. Helen Alice  31.00
1266                           Bowen, Miss. Grace Scott  45.00
1291                            Bonnell, Miss. Caroline  30.00
1305                       Oliva y Ocana, Dona. Fermina  39.00

In [53]:
# find the name and age of Children (<15) in 3rd class

print(df[(df["Age"] < 15) & (df["Pclass"] == 3)][["Name", "Age"]])

                                      Name   Age
7           Palsson, Master. Gosta Leonard   2.0
10         Sandstrom, Miss. Marguerite Rut   4.0
14    Vestrom, Miss. Hulda Amanda Adolfina  14.0
16                    Rice, Master. Eugene   2.0
24           Palsson, Miss. Torborg Danira   8.0
...                                    ...   ...
1251           Sage, Master. William Henry  14.5
1270           Asplund, Master. Carl Edgar   5.0
1280           Palsson, Master. Paul Folke   6.0
1283         Abbott, Master. Eugene Joseph  13.0
1300             Peacock, Miss. Treasteall   3.0

[75 rows x 2 columns]

In [54]:
# Count passengers older than 60
df.loc[df["Age"] > 60, :].shape[0]

33