In [82]:
import pandas as pd
import numpy as np

In [83]:
data = {
'Department': ['IT', 'HR', 'IT', 'Finance', 'HR', 'Finance', 'IT'],
'Employee': ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
'Salary': [50000, 40000, 55000, 60000, 42000, 65000, 58000],
'Experience': [2, 1, 3, 5, 2, 6, 4]
}


df = pd.DataFrame(data)
df

  Department Employee  Salary  Experience
0         IT        A   50000           2
1         HR        B   40000           1
2         IT        C   55000           3
3    Finance        D   60000           5
4         HR        E   42000           2
5    Finance        F   65000           6
6         IT        G   58000           4

3. What is GroupBy?

groupby() is used to split data into groups, apply a function, and combine results.

Split → Apply → Combine

Basic GroupBy (Single Column)
Group by Department

In [84]:
df.groupby('Department')

In [85]:
df.groupby('Department')['Salary'].mean()
#Calculate Mean Salary per Department

Department
Finance    62500.000000
HR         41000.000000
IT         54333.333333
Name: Salary, dtype: float64

In [86]:
# Multiple Aggregations
df.groupby('Department')['Salary'].agg(['mean', 'max', 'min', 'sum'])

                    mean    max    min     sum
Department
Finance     62500.000000  65000  60000  125000
HR          41000.000000  42000  40000   82000
IT          54333.333333  58000  50000  163000

In [87]:
# GroupBy with Multiple Columns
df.groupby(['Department', 'Experience'])['Salary'].mean()

Department  Experience
Finance     5             60000.0
            6             65000.0
HR          1             40000.0
            2             42000.0
IT          2             50000.0
            3             55000.0
            4             58000.0
Name: Salary, dtype: float64

In [88]:
df.groupby('Department')['Employee'].count()
#Using GroupBy with Count

Department
Finance    2
HR         2
IT         3
Name: Employee, dtype: int64

In [89]:
def salary_range(x):
 return x.max() - x.min()


df.groupby('Department')['Salary'].apply(salary_range)

Department
Finance    5000
HR         2000
IT         8000
Name: Salary, dtype: int64

In [90]:
# titanic datasets

In [91]:
import pandas as pd

df = pd.read_csv("/content/titanic_dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [92]:
#Average Fare per Passenger Class
df.groupby('Pclass')['Fare'].mean()

Pclass
1    87.508992
2    21.179196
3    13.302889
Name: Fare, dtype: float64

In [93]:
df.groupby('Sex')['Survived'].mean()
#Survival Rate by Gender

Sex
female    0.82618
male      0.12930
Name: Survived, dtype: float64

In [94]:
# Multiple Aggregations
df.groupby('Pclass')['Fare'].agg(['mean', 'max', 'min', 'count'])

             mean       max  min  count
Pclass
1       87.508992  512.3292  0.0    323
2       21.179196   73.5000  0.0    277
3       13.302889   69.5500  0.0    708

In [95]:
#GroupBy Multiple Columns
df.groupby(['Pclass', 'Sex'])['Survived'].mean()

Pclass  Sex
1       female    0.979167
        male      0.251397
2       female    0.943396
        male      0.099415
3       female    0.666667
        male      0.095335
Name: Survived, dtype: float64

In [96]:
# Average age of survivors vs non-survivors
df.groupby('Survived')['Age'].mean()

Survived
0    30.510986
1    28.931079
Name: Age, dtype: float64

In [97]:
# Count of male and female passengers per class
df.groupby(['Pclass', 'Sex']).size()

Pclass  Sex
1       female    144
        male      179
2       female    106
        male      171
3       female    216
        male      493
dtype: int64

In [98]:
df["average age "]=df.groupby("Sex")["Age"].mean()

In [99]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,average age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,NaN
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,NaN
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,NaN
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,NaN
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,NaN
1307,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,NaN
1308,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,NaN

In [100]:


# Which embark town has highest survival rate?

df.groupby("Embarked")["Age"].mean()

Embarked
C    32.332170
Q    28.630000
S    29.245205
Name: Age, dtype: float64

Now your task is to make a 25 question from chatgpt and practcie your self furst write the question and then answer

In [101]:
print(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'average age '],
      dtype='object')

In [102]:
# 1. What is the average age for each gender?

df.groupby("Sex")["Age"].mean()

Sex
female    28.687088
male      30.585228
Name: Age, dtype: float64

In [103]:
# 2. What is the average fare for each passenger class?

df.groupby("Pclass")["Fare"].mean()

Pclass
1    87.508992
2    21.179196
3    13.302889
Name: Fare, dtype: float64

In [104]:
# 3. What is the survival rate for each gender?

df.groupby("Sex")["Survived"].mean()

Sex
female    0.82618
male      0.12930
Name: Survived, dtype: float64

In [105]:
# 4. What is the average fare for each gender?

df.groupby("Sex")["Fare"].mean()

Sex
female    46.198097
male      26.154601
Name: Fare, dtype: float64

In [106]:
# 5. What is the maximum fare for each passenger class?

df.groupby("Pclass")["Fare"].max()

Pclass
1    512.3292
2     73.5000
3     69.5500
Name: Fare, dtype: float64

In [107]:
# 6. What is the minimum fare for each passenger class?

df.groupby("Pclass")["Fare"].min()

Pclass
1    0.0
2    0.0
3    0.0
Name: Fare, dtype: float64

In [108]:
# 7. What is the total fare paid by passengers in each passenger class?

df.groupby("Pclass")["Fare"].sum()

Pclass
1    28265.4043
2     5866.6374
3     9418.4452
Name: Fare, dtype: float64

In [109]:
# 8. How many passengers are there in each passenger class?

df.groupby("Pclass")["PassengerId"].count()

Pclass
1    323
2    277
3    709
Name: PassengerId, dtype: int64

In [110]:
# 9. Find the mean, maximum, minimum, and total fare for each passenger class.

df.groupby("Pclass")["Fare"].agg(
    ["mean", "max", "min", "sum"]
)

             mean       max  min         sum
Pclass
1       87.508992  512.3292  0.0  28265.4043
2       21.179196   73.5000  0.0   5866.6374
3       13.302889   69.5500  0.0   9418.4452

In [111]:
# 10. Find the mean, maximum, minimum, and count of fares for each gender.

df.groupby("Sex")["Fare"].agg(
    ["mean", "max", "min", "count"]
)

             mean       max   min  count
Sex
female  46.198097  512.3292  6.75    466
male    26.154601  512.3292  0.00    842

In [112]:
# 11. Find the survival rate for each combination of passenger class and gender.

df.groupby(
    ["Pclass", "Sex"]
)["Survived"].mean()

Pclass  Sex
1       female    0.979167
        male      0.251397
2       female    0.943396
        male      0.099415
3       female    0.666667
        male      0.095335
Name: Survived, dtype: float64

In [113]:
# 12. Find the average age for each combination of passenger class and gender.

df.groupby(
    ["Pclass", "Sex"]
)["Age"].mean()

Pclass  Sex
1       female    37.037594
        male      41.029272
2       female    27.499223
        male      30.815380
3       female    22.185329
        male      25.962264
Name: Age, dtype: float64

In [114]:
# 13. Find the average fare for each combination of passenger class and gender.

df.groupby(
    ["Pclass", "Sex"]
)["Fare"].mean()

Pclass  Sex
1       female    109.412385
        male       69.888385
2       female     23.234827
        male       19.904946
3       female     15.324250
        male       12.415462
Name: Fare, dtype: float64

In [115]:
# 14. Find the average age of survivors and non-survivors.

df.groupby("Survived")["Age"].mean()

Survived
0    30.510986
1    28.931079
Name: Age, dtype: float64

In [116]:
# 15. Find the average fare paid by survivors and non-survivors.

df.groupby("Survived")["Fare"].mean()

Survived
0    23.879124
1    48.811497
Name: Fare, dtype: float64

In [117]:
# 16. Count the number of male and female passengers in each passenger class.

df.groupby(
    ["Pclass", "Sex"]
).size()

Pclass  Sex
1       female    144
        male      179
2       female    106
        male      171
3       female    216
        male      493
dtype: int64

In [118]:
# 17. Count the number of survivors and non-survivors in each passenger class.

df.groupby(
    ["Pclass", "Survived"]
).size()

Pclass  Survived
1       0           137
        1           186
2       0           160
        1           117
3       0           518
        1           191
dtype: int64

In [119]:
# 18. Find the average age for each embarkation town.

df.groupby("Embarked")["Age"].mean()

Embarked
C    32.332170
Q    28.630000
S    29.245205
Name: Age, dtype: float64

In [120]:
# 19. Find the average fare for each embarkation town.

df.groupby("Embarked")["Fare"].mean()

Embarked
C    62.336267
Q    12.409012
S    27.418824
Name: Fare, dtype: float64

In [121]:
# 20. Find the survival rate for each embarkation town.

df.groupby("Embarked")["Survived"].mean()

Embarked
C    0.492593
Q    0.439024
S    0.333698
Name: Survived, dtype: float64

In [122]:
# 21. Find the average age, minimum age, and maximum age for each gender.

df.groupby("Sex")["Age"].agg(
    ["mean", "min", "max"]
)

             mean   min   max
Sex
female  28.687088  0.17  76.0
male    30.585228  0.33  80.0

In [123]:
# 22. Find the average fare and survival rate for each passenger class.

df.groupby("Pclass").agg(
    average_fare=("Fare", "mean"),
    survival_rate=("Survived", "mean")
)

        average_fare  survival_rate
Pclass
1          87.508992       0.575851
2          21.179196       0.422383
3          13.302889       0.269394

In [124]:
# 23. Find the average fare and average age for each gender.

df.groupby("Sex").agg(
    average_fare=("Fare", "mean"),
    average_age=("Age", "mean")
)

        average_fare  average_age
Sex
female     46.198097    28.687088
male       26.154601    30.585228

In [125]:
# 24. Create a function to calculate the age range for each passenger class.

def age_range(x):
    return x.max() - x.min()

df.groupby("Pclass")["Age"].apply(age_range)

Pclass
1    79.08
2    69.33
3    73.83
Name: Age, dtype: float64

In [126]:
# 25. Create a new column containing the average age for each gender.

df["average age "] = df.groupby("Sex")["Age"].transform("mean")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,average age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,30.585228
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,28.687088
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,28.687088
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,28.687088
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,30.585228

In [127]:
import pandas as pd

df1 = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['A', 'B', 'C']
})
df1

   id name
0   1    A
1   2    B
2   3    C

In [128]:
df1

   id name
0   1    A
1   2    B
2   3    C

In [129]:
df2 = pd.DataFrame({
    'id': [1, 2, 4],
    'score': [85, 90, 88]
})

In [130]:
df2

   id  score
0   1     85
1   2     90
2   4     88

In [131]:
result = pd.merge(df1, df2, on='id')
print(result)

   id name  score
0   1    A     85
1   2    B     90

In [132]:
pd.merge(df1, df2, on='id', how='inner')
#Keeps common rows only

   id name  score
0   1    A     85
1   2    B     90

In [133]:
# Test with new data
import pandas as pd

students = pd.DataFrame({
    'student_id': [101, 102, 103, 104],
    'student_name': ['Ram', 'Sita', 'Hari', 'Gita'],
    'department': ['CS', 'IT', 'CS', 'BCA']
})

print(students)

   student_id student_name department
0         101          Ram         CS
1         102         Sita         IT
2         103         Hari         CS
3         104         Gita        BCA

In [134]:
marks = pd.DataFrame({
    'student_id': [101, 102, 105],
    'marks': [88, 92, 75]
})

print(marks)

   student_id  marks
0         101     88
1         102     92
2         105     75

In [135]:
inner_join = pd.merge(students, marks, on='student_id', how='inner')
print(inner_join)
# Common records only

   student_id student_name department  marks
0         101          Ram         CS     88
1         102         Sita         IT     92

In [136]:
left_join = pd.merge(students, marks, on='student_id', how='left')
print(left_join)

   student_id student_name department  marks
0         101          Ram         CS   88.0
1         102         Sita         IT   92.0
2         103         Hari         CS    NaN
3         104         Gita        BCA    NaN

In [137]:
right_join = pd.merge(students, marks, on='student_id', how='right')
print(right_join)

   student_id student_name department  marks
0         101          Ram         CS     88
1         102         Sita         IT     92
2         105          NaN        NaN     75

In [138]:
outer_join = pd.merge(students, marks, on='student_id', how='outer')
print(outer_join)
# Outer Join (Everything from both tables)

   student_id student_name department  marks
0         101          Ram         CS   88.0
1         102         Sita         IT   92.0
2         103         Hari         CS    NaN
3         104         Gita        BCA    NaN
4         105          NaN        NaN   75.0

Easy Memory Trick

Inner → common only

Left → everything from first table

Right → everything from second table

Outer → everything from both