In [3]:
# 1️⃣ Import Pandas Library
# Import pandas to work with DataFrames
import pandas as pd

In [4]:
# 2️⃣ Create a Sample DataFrame
# We will create a DataFrame with columns 'Name', 'Age', 'City'
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar']
}

df = pd.DataFrame(data)  # Create DataFrame
df

      Name  Age        City
0    Alice   25   Kathmandu
1      Bob   30     Pokhara
2  Charlie   35    Lalitpur
3    David   40  Biratnagar

In [5]:
# 3️⃣ Default Index
# By default, Pandas assigns a numeric index starting from 0
print(df.index)  # Shows the default index

RangeIndex(start=0, stop=4, step=1)

# 4️⃣ Set a Column as Index

In [6]:
df.set_index("Name")

         Age        City
Name
Alice     25   Kathmandu
Bob       30     Pokhara
Charlie   35    Lalitpur
David     40  Biratnagar

permanently set index

In [7]:
df.set_index("Name",inplace=True)

In [8]:
df

         Age        City
Name
Alice     25   Kathmandu
Bob       30     Pokhara
Charlie   35    Lalitpur
David     40  Biratnagar

In [9]:
# 6️⃣ Reset Index

df.reset_index()

      Name  Age        City
0    Alice   25   Kathmandu
1      Bob   30     Pokhara
2  Charlie   35    Lalitpur
3    David   40  Biratnagar

In [10]:
# 6️⃣ Reset Index

df.reset_index(inplace=True)

### What does inplace=True mean?

- `inplace=True` means **modify the original DataFrame**
- No new DataFrame is created
- Changes happen **permanently**

### Example:
Without inplace:
```python
new_df = df.set_index("Student_ID")

In [11]:
import pandas as pd
# Creating a simple DataFrame
data = {
    "Student_ID": [101, 102, 103, 104],
    "Name": ["Ram", "Sita", "Hari", "Gita"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)

# Display the DataFrame
df

   Student_ID  Name  Marks
0         101   Ram     85
1         102  Sita     90
2         103  Hari     78
3         104  Gita     92

In [12]:
df.set_index("Student_ID")

            Name  Marks
Student_ID
101          Ram     85
102         Sita     90
103         Hari     78
104         Gita     92

In [13]:
df.set_index("Student_ID", inplace=True)

In [14]:
df

            Name  Marks
Student_ID
101          Ram     85
102         Sita     90
103         Hari     78
104         Gita     92

task create a one data and practcie all like make index reset test with inplace

In [15]:
# 1. Create the DataFrame

import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["suman", "Siwani", "Hira", "Ganga", "jerry"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 90, 78, 92, 88]
}

df = pd.DataFrame(data)

df

   Student_ID    Name  Age  Marks
0         101   suman   20     85
1         102  Siwani   21     90
2         103    Hira   19     78
3         104   Ganga   22     92
4         105   jerry   20     88

In [16]:
# 2. Check the default index

df.index

RangeIndex(start=0, stop=5, step=1)

In [17]:
# 3. Set Student_ID as the index

df.set_index("Student_ID")

              Name  Age  Marks
Student_ID
101          suman   20     85
102         Siwani   21     90
103           Hira   19     78
104          Ganga   22     92
105          jerry   20     88

In [18]:
df

   Student_ID    Name  Age  Marks
0         101   suman   20     85
1         102  Siwani   21     90
2         103    Hira   19     78
3         104   Ganga   22     92
4         105   jerry   20     88

In [19]:
# 4. Set Student_ID as the index permanently

df.set_index("Student_ID", inplace=True)

df

              Name  Age  Marks
Student_ID
101          suman   20     85
102         Siwani   21     90
103           Hira   19     78
104          Ganga   22     92
105          jerry   20     88

In [20]:
# 5. Select a row using the index

df.loc[103]

Name     Hira
Age        19
Marks      78
Name: 103, dtype: object

In [21]:
# 6. Select multiple rows using the index

df.loc[[102, 104]]

              Name  Age  Marks
Student_ID
102         Siwani   21     90
104          Ganga   22     92

In [22]:
# 7. Reset the index without inplace

df.reset_index()

   Student_ID    Name  Age  Marks
0         101   suman   20     85
1         102  Siwani   21     90
2         103    Hira   19     78
3         104   Ganga   22     92
4         105   jerry   20     88

In [23]:
df

              Name  Age  Marks
Student_ID
101          suman   20     85
102         Siwani   21     90
103           Hira   19     78
104          Ganga   22     92
105          jerry   20     88

In [24]:
# 8.Reset the index using inplace=True

df.reset_index(inplace=True)

df

   Student_ID    Name  Age  Marks
0         101   suman   20     85
1         102  Siwani   21     90
2         103    Hira   19     78
3         104   Ganga   22     92
4         105   jerry   20     88

In [25]:
# 9. Set Name as the index

df.set_index("Name", inplace=True)

df

        Student_ID  Age  Marks
Name
suman          101   20     85
Siwani         102   21     90
Hira           103   19     78
Ganga          104   22     92
jerry          105   20     88

In [26]:
df.loc["Ganga"]

Student_ID    104
Age            22
Marks          92
Name: Ganga, dtype: int64

In [27]:
# Set Student_ID as the index, display the DataFrame, then reset the index back to the default index.

df.reset_index(inplace=True)

df.set_index("Student_ID", inplace=True)

print("After setting Student_ID as index:")
print(df)

df.reset_index(inplace=True)

print("After resetting index:")
print(df)

After setting Student_ID as index:
              Name  Age  Marks
Student_ID
101          suman   20     85
102         Siwani   21     90
103           Hira   19     78
104          Ganga   22     92
105          jerry   20     88
After resetting index:
   Student_ID    Name  Age  Marks
0         101   suman   20     85
1         102  Siwani   21     90
2         103    Hira   19     78
3         104   Ganga   22     92
4         105   jerry   20     88